# Generated by Django 5.0.2 on 2024-02-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_field',
            new_name='date_added',
        ),
    ]
